trigger:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'

pr:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'

pool:
  vmImage: windows-2019

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview5-011323'

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- task: MSBuild@1
  displayName: Build for $(BuildConfiguration)
  inputs:
    solution: WpfCoreApp.sln
    msbuildArguments: /restore
    configuration: $(BuildConfiguration)
    maximumCpuCount: false

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: Package
    targetPath: WpfCoreApp.Package/AppPackages/WpfCoreApp.Package_*/