trigger:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'

pr:
  branches:
    include:
    - master
    - rel/*
  paths:
    exclude:
    - '**/*.md'

pool:
  vmImage: windows-2019

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview5-011323'

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- powershell: |
    # Get the version version    
    $ver = .\nbgv get-version -f json | ConvertFrom-Json
    
    # Update appxmanifest. This must be done before build.
    $doc = Get-Content ".\WpfCoreApp.Package\Package.appxmanifest"    
    $doc | % { $_.Replace("1.0.0", "$($ver.CloudBuildVersionVars.GitBuildVersionSimple)") } | Set-Content ".\WpfCoreApp.Package\Package.appxmanifest"    
  displayName: Update manifest version

- task: MSBuild@1
  displayName: Build for $(BuildConfiguration)
  inputs:
    solution: WpfCoreApp.sln
    msbuildArguments: /restore 
    configuration: $(BuildConfiguration)
    maximumCpuCount: false

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: Package
    targetPath: WpfCoreApp.Package/AppPackages
    
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: PublicCert
    targetPath: build.cer   